service: bus-lviv-bot
provider:
  name: aws
  runtime: nodejs8.10
  stage: production

functions:
  bot:
    handler: serverless_bot.handler
    events:
      - http:
          path: bot
          method: any